<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
  <?php include_once('includes/sidebar.php');?>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
<?php include_once('includes/topbar.php');?>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-2 text-gray-800">Touts les tests</h1>
    

                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Les nouveaux tests</h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <form name="assignto" method="post">
                    <table class="table table-bordered"  width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                           
                                            <th>Num</th> 
                                            <th>Nom de patient</th>
                                            <th>Téléphone</th>
                                            <th>Type de test</th>
                                            <th>Créneau horaire</th>
                                            <th>Date de demande test</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                      
                                    <tbody>
<?php 
    $index=0;
    foreach ($AssignedTests as $test) :
        $index++;
?>
            
                                        <tr>
                                            <td><?php echo $index;?></td>
                                        
                                            <td><?php echo $test['FullName'];?></td>
                                            <td><?php echo $test['mobile'];?></td>
                                            <td><?php echo $test['nomTest'];?></td>
                                            <td><?php echo $test['TestTimeSlot'];?></td>
                                             <td><?php echo $test['RegistrationDate'];?></td>
                                            <td>
                                    
                                <a href="testDetailsV2.php?tid=<?php echo $test['id'];?>" class="btn btn-info btn-sm">Consultez les détails</a> 

                            </td>
                                        </tr>
<?php endforeach; ?>
                                    </tbody>
                                </table>
                                     </form>
                            </div>
                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->


            <!-- Footer -->
    <?php include_once('includes/footer.php');?>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <?php include_once('includes/footer2.php');?>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="js/demo/datatables-demo.js"></script>
</body>