<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

<?php include_once('includes/sidebar.php');?>

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
          <?php include_once('includes/topbar.php');?>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
<?php 
$tid=intval($_GET['tid']);
$query = $pdo->query("SELECT * from techniciens where id='$tid'");
$technicien = $query->fetch();

?>                 
<h1 class="h3 mb-4 text-gray-800">Profile de <?php echo $technicien['FullName'];?></h1>
<form name="editphlebotomist" method="post">
  <div class="row">

                        <div class="col-lg-8">

                            <!-- Basic Card Example -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">Information personnelles</h6>
                                </div>
                                <div class="card-body">

 <div class="form-group">
                            <label>Date d'inscription à COVID19-TMS: </label>

                                     <?php echo $technicien['dateRegistration'];?>        
                                        </div>

                  <div class="form-group">
                            <label>CIN technicien</label>
                             <input type="text" class="form-control" id="empid" name="empid"  value="<?php echo $technicien['techID'];?>"  readonly="true" >
                                             
                                        </div>

                        <div class="form-group">
                            <label>Nom et Prénom</label>
                                            <input type="text" class="form-control" id="fullname" name="fullname"  placeholder="Enter your full name..." pattern="[A-Za-z ]+" title="letters only" value="<?php echo $technicien['FullName'];?>" required="true">
                                        </div>
                                        <div class="form-group">
                                             <label>Numéro de téléphone</label>
                                  <input type="text" class="form-control" id="mobilenumber" name="mobilenumber" placeholder="Please enter your mobile number" pattern="[0-9]{10}" title="10 numeric characters only" value="<?php echo $technicien['MobilePhone'];?>" required="true" >
                                          
                                        </div>
                        


        <div class="form-group">
                                 <input type="submit" class="btn btn-primary btn-user btn-block" name="update" id="update" value="Valider">                           
                             </div>                                        

                                </div>
                            </div>

                        </div>
                    </div>
</form>


                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

           <?php include_once('includes/footer.php');?>

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
   <?php include_once('includes/footer2.php');?>


    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>