<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
  <?php include_once('includes/sidebar.php');?>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
<?php include_once('includes/topbar.php');?>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-2 text-gray-800">Gérer les techniciens</h1>
    

                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Informations des techniciens </h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered"  width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            
                                            <th>CIN technicien</th>
                                            <th>Nom et Prénom</th>
                                            <th>Téléphone</th>
                                            <th>Date d'inscription à COVID19-TMS</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    
                                    <tbody>


                                    <?php foreach ($techniciens as $technicien) : ?>
                                       
                                    
                                        <tr>
                                            
                                            <td><?php echo $technicien['techID'];?></td>
                                            <td><?php echo $technicien['FullName'];?></td>
                                            <td><?php echo $technicien['MobilePhone'];?></td>
                                             <td><?php echo $technicien['dateRegistration'];?></td>
                                            <td>
                                            <a href="editerTechnicien.php?tid=<?php echo $technicien['id'];?>"><i class="fas fa-edit" style="color:blue"></i></a> |

                                            <a href="gererTechniciens.php?pid=<?php echo $technicien['id'];?>&&action=delete" onclick="return confirm('Voulez-vous réellement supprimer ce technicien ?');"><i class="fa fa-trash" aria-hidden="true" style="color:red" title="Delete this record"></i></a></td>
                                                    
                               
                                        </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
    <?php include_once('includes/footer.php');?>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <?php include_once('includes/footer2.php');?>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="js/demo/datatables-demo.js"></script>
</body>