<body id="page-top">
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top"><i class="fas fa-fw fa-virus"></i> Covid19-TMS</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#about">A propos de Covid-19</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#services">Les symptomes de Covid-19</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#contact">La prévention</a>
          </li>
  <li class="nav-item active">
            <a class="nav-link js-scroll-trigger" href="new-user.php">Analyse</a>
          </li>
          

           <li class="nav-item active">
            <a class="nav-link js-scroll-trigger" href="loginAdmin.php">Admin</a>
          </li>


        </ul>
      </div>
    </div>
  </nav>

  </nav>
<header class=" text-white" style="background-image:url(img/bg.png)">
    <!--<div class="container text-center">
      <h1> COVID19-TMS</h1>
      <p class="lead">COVID19 - Testing Management System</p>
    </div>-->
    <!-- slider section -->
    <section class="slider_section ">
      <div id="customCarousel1" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="container ">
              <div class="row">
                <div class="col-md-7 col-lg-6 ">
                  <div class="detail-box" data-aos="fade-right"  data-aos-duration="1500">
                    <h1>
                      COVID19-TMS
                    </h1>
                    <p>
                     En réponse à la pandémie de COVID-19 et à la nécessité d'informer
                       immédiatement les patients des résultats de leurs tests, nous présentons COVID19-TMS - une application 
                       complète de gestion des tests COVID-19 de bout en bout qui élimine les processus manuels avec une conformité 
                    réglementaire totale et des notifications automatisées des résultats des tests.
                    </p>
                    
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div> 
      </div>
    
    </section>
    <!-- end slider section -->
			
  </header>

  <section id="about">
    <div class="container">
      <div class="row">
 
        <div class="col-lg-8 mx-auto" data-aos="fade-right"  data-aos-duration="1500">
       
          <h2><i class="fas fa-fw fa-virus"></i> Coronavirus : qu'est-ce que c'est ?</h2>
          <p class="lead">Covid-19 fait référence à « Coronavirus Disease 2019 », la maladie provoquée par un virus de la famille des Coronaviridae, le SARS-CoV-2. Cette maladie infectieuse est une zoonose, dont l'origine est encore débattue, qui a émergé en décembre 2019 dans la ville de Wuhan, dans la province du Hubei en Chine. Elle s'est rapidement propagée, d'abord dans toute la Chine, puis à l'étranger provoquant une épidémie mondiale.</p>
          <p class="lead">Le Covid-19 est une maladie respiratoire pouvant être mortelle chez les patients fragilisés par l'âge ou une autre maladie chronique. Elle se transmet par contact rapproché avec des personnes infectées. La maladie pourrait aussi être transmise par des patients asymptomatiques mais les données scientifiques manquent pour en attester avec certitude.</p>
         
        </div>
      </div>
    </div>
  </section>

  <section id="services" class="bg-light">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto" data-aos="fade-right"  data-aos-duration="1500">
          <h2><i class="fas fa-hospital"></i>  Les symptômes de la maladie Covid-19</h2>
          <br /><br />
            <p>Toux<br />
            
                      
            <p>Fatigue<br />
            
            <p>Perte de l'odorat ou du gout<br />
            <p>Maux de gorge<br />
            <p>Maux de tete<br />
            <p>Courbatures<br />
        </div>
      </div>
    </div>
  </section>

  <section id="contact">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto" data-aos="fade-right"  data-aos-duration="1500">
          <h2><i class="fas fa-head-side-mask"></i>  La prévention</h2>
          <ul>
            <li>Lavez-vous les mains souvent</li>
            <li>Portez des bavettes</li>
            <li>Evitez le contact avec des personnes malades</li>
            <li>Couvrez toujours votre toux ou vos éternuements</li>
          </ul>
        </div>
      </div>
    </div>
  </section>
   <!-- Footer -->
   <footer class="py-5 bg-dark">
    <div class="container">
      
    </div>
    <!-- /.container -->
  </footer>
  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Plugin JavaScript -->
  <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom JavaScript for this theme -->
  <script src="js/scrolling-nav.js"></script>
  <script src="https://kit.fontawesome.com/949a20bb4a.js" crossorigin="anonymous"></script>
  <!-- jQuery -->
	<script src="js/jquery.min.js"></script>
	<!-- jQuery Easing -->
	<script src="js/jquery.easing.1.3.js"></script>
	<!-- Bootstrap -->
	<script src="js/bootstrap.min.js"></script>
	<!-- Waypoints -->
	<script src="js/jquery.waypoints.min.js"></script>
	<!-- Flexslider -->
	<script src="js/jquery.flexslider-min.js"></script>
  <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
  <script>
  AOS.init();
</script>
</body>

