<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

<?php include_once('includes/sidebar.php');?>

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
          <?php include_once('includes/topbar.php');?>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-4 text-gray-800">Admin Profile</h1>
     <form method="post"  name="adminprofile" >



  <div class="row">

                        <div class="col-lg-8">

                            <!-- Basic Card Example -->
                            <div class="card shadow mb-4">

               

            


                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">Registration Date: <?php  echo $admin['dateRegistration'];?></h6>
                                </div>
                                <div class="card-body">
     

                        <div class="form-group">
                            <label>Nom admin</label>
                       <input type="text" class="form-control" name="username" value="<?php  echo $admin['userName'];?>" readonly='true'> 
                                        </div>
                                        
<div class="form-group">
<label>Email </label>
<input type="email" class="form-control" name="email" value="<?php  echo $admin['mail'];?>" required='true'>
</div>

<div class="form-group">
<label>Numéro de téléphone</label>
<input type="text" class="form-control" name="mobilenumber" value="<?php  echo $admin['mobilePhone'];?>" required='true' maxlength='10'>
</div>
                        


        <div class="form-group">
                                 <input type="submit" class="btn btn-primary btn-user btn-block" name="update" id="update" value="Update">                           
                             </div>                                        

                                </div>
                            </div>

                        </div>

               

                    </div>
</form>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

           <?php include_once('includes/footer.php');?>

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->

           <?php include_once('includes/footer2.php');?>


    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>