<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Covid-19 Testing Management System</title>

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="css/sb-admin-2.min.css" rel="stylesheet">
    <style type="text/css">
        label {
            font-size: 16px;
            font-weight: bold;
            color: #000;
        }
    </style>
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <?php include_once('includes/sidebar.php');?>

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <?php include_once('includes/topbar.php');?>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-4 text-gray-800">Covid19-Testing | Already Registeres Users</h1>

                    <form method="post">
                        <div class="row">

                            <div class="col-lg-6">

                                <!-- Basic Card Example -->
                                <div class="card shadow mb-4">

                                    <div class="card-body">
                                        <div class="form-group">
                                            <label>Registered CIN Number</label>
                                            <input type="tel" class="form-control" name="regcinnumber"
                                                placeholder="Please enter your registered cin number" required>
                                        </div>
                                        <div class="form-group">
                                            <input type="submit" class="btn btn-primary btn-user btn-block"
                                                name="search" value="Search">
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                    <hr />
                    <?php if(isset($_POST['search'])){ ?>
                    <h3 align="center" style="color:red">Resulst againt cin number
                        "<?php echo $_POST['regcinnumber'];?>"</h3>
                    <hr />
                    <?php
    if($row>0){
        
        
    while ($result=$stmt->fetch(PDO::FETCH_ASSOC)) {
      

?>

                    <form name="newtesting" method="post" action="registred-user.php">
                        <div class="row">

                            <div class="col-lg-6">

                                <!-- Basic Card Example -->
                                <div class="card shadow mb-4">
                                    <div class="card-header py-3">
                                        <h6 class="m-0 font-weight-bold text-primary">Personal Information</h6>
                                    </div>
                                    <div class="card-body">
                                        <div class="form-group">
                                            <label>Nom & Prenom</label>
                                            <input type="text" class="form-control" id="fullname" name="fullname"
                                            readonly="true" value="<?php echo $result['FullName']; ?>" >
                                        </div>
                                        <div class="form-group">
                                            <label>Num Téléphone</label>
                                            <input type="tel" class="form-control" name="mobilenumber"
                                            readonly="true" value="<?php echo $result['mobile']; ?>" >
                                        </div>
                                        <div class="form-group">
                                            <label>Date d'anniversaire</label>
                                            <input type="text" class="form-control" name="dob" 
                                            readonly="true" value="<?php echo $result['dateannif']; ?>">
                                        </div>
                                        <div class="form-group">
                                            <label>CIN</label>
                                            <input type="tel" class="form-control" id="govtissuedid" name="cin"
                                            readonly="true"  value="<?php echo $result['cin']; ?>" >
                                        </div>

                                        <div class="form-group">
                                            <label>Address</label>
                                            <textarea class="form-control" id="address" name="address"
                                                readonly="true"><?php echo $result['adresse']; ?></textarea>
                                        </div>
                                        <div class="form-group">
                                            <label>State</label>
                                            <input type="text" class="form-control" id="state" name="state"
                                            readonly="true"  value="<?php echo $result['state']; ?>">
                                        </div>

                                    </div>
                                </div>

                            </div>

                            <div class="col-lg-6">

                                <div class="card shadow mb-4">
                                    <div class="card-header py-3">
                                        <h6 class="m-0 font-weight-bold text-primary">Testing Information</h6>
                                    </div>
                                    <div class="card-body">
                                        <div class="form-group">
                                            <label>Test Type</label>
                                            <select class="form-control" id="testtype" name="testtype" required="true">
                                            <?php foreach ($typeTest as $type) : ?>
                                                <option><?php echo $type['nomTest']; ?></option>
                                            <?php endforeach; ?>

                                            </select>
                                        </div>

                                        <div class="form-group">
                                            <label>Fuseau horaire pour le test</label>
                                            <input type="datetime-local" class="form-control" name="fhd"
                                                class="form-control">
                                        </div>
                                        <div class="form-group">
                                            <input type="submit" class="btn btn-primary btn-user btn-block"
                                                name="submit" id="submit">
                                        </div>

                                    </div>
                                </div>


                            </div>

                        </div>
                    </form>
                    <?php 
                  
                } } else { ?>
                    <h4 align="center" style="color:red;">No record found</h4>
                    <?php }}?>



                    <!-- End of Main Content -->

                    <?php include_once('includes/footer.php');?>

                </div>
                <!-- End of Content Wrapper -->

            </div>
            <!-- End of Page Wrapper -->

            <!-- Scroll to Top Button-->
            <a class="scroll-to-top rounded" href="#page-top">
                <i class="fas fa-angle-up"></i>
            </a>



            <!-- Bootstrap core JavaScript-->
            <script src="vendor/jquery/jquery.min.js"></script>
            <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

            <!-- Core plugin JavaScript-->
            <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

            <!-- Custom scripts for all pages-->
            <script src="js/sb-admin-2.min.js"></script>

</body>

</html>