<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

    <?php include_once('includes/sidebar.php');?>

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <?php include_once('includes/topbar.php');?>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-4 text-gray-800">Details test# <?php echo intval($_GET['tid']);?></h1>
<div class="row">

<!-- personal information --->
                        <div class="col-lg-6">

                            <!-- Basic Card Example -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">Informations personnelles</h6>
                                </div>
                                <div class="card-body">
   
 <table class="table table-bordered"  width="100%" cellspacing="0">
    <tr>
    <th>Nom et Prénom</th> 
    <td><?php echo $dataPatients['FullName'];?></td>
    </tr>

     <tr>
    <th>Numéro de téléphone</th> 
    <td><?php echo $dataPatients['mobile'];?></td>
    </tr>

     <tr>
    <th>Date de naissance</th> 
    <td><?php echo $dataPatients['dateannif'];?></td>
    </tr>

    <tr>
    <th>Adresse</th> 
    <td><?php echo $dataPatients['adresse'].' '.$dataPatients['state'];?></td>
    </tr>
    <tr>
    <th>Date d'inscription à la plateforme COVID19-TMS</th> 
    <td><?php echo $dataPatients['registrationDate'];?></td>
    </tr>
 </table>

        
                                    
                                </div>
                            </div>
                        </div>
                     
            <!-- Test Information --->
              
                 
                
                         <div class="col-lg-6">

                            <!-- Basic Card Example -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">Informations test</h6>
                                </div>
                                <div class="card-body">

 <table class="table table-bordered"  width="100%" cellspacing="0">

    <tr>
    <th>Type test</th> 
    <td><?php echo $typeTest['nomTest'];?></td>
    </tr>


    <tr>
    <th>Créneau horaire</th> 
    <td><?php echo $dataTests['TestTimeSlot'];?></td>
    </tr>

 <tr>
    <th>Résultat</th> 
    <td><?php if($dataTests['resultat']==NULL):
              echo "Aucun résultat disponible";
          else:
           echo $dataTests['resultat'];
          endif;

    ?></td>
    </tr>

    <?php if($dataTests['assigned']=='0'):?>
  <tr>
    <th>Affecté à</th> 
    <td>Pas encore affecté</td>
    </tr>
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Affecter à un technicien
</button>
    <?php endif;?>
<?php if($dataTests['assigned']=='1'):?>
  <tr>
    <th>Affecté à</th> 
    <td><?php echo $dataTech['FullName']; ?></td>
    </tr>

    <tr>
    <th>Date d'affectation</th> 
    <td><?php echo $dataTests['assignedTime'];?></td>
    </tr>
<?php endif;?>

    
    <div class="form-group">
        
  

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
       <form action="testDetailsV2.php?tid=<?php echo $dataTests['id'];?>" method="post">
          <label for="tech">Techniciens</label>
          <select name="tech">
              
                 <?php foreach ($techniciens as $technicien) :  ?>
                  <option> <?php echo $technicien['FullName']; ?></option>
                  <?php endforeach; ?>
          </select>
          <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <!-- ou bien button à verifier -->
        
        <input type="submit" class="btn btn-primary btn-user btn-block" name="submit" value="Affecter" id="submit">  
        
     <!--   <button type="submit" class="btn btn-primary" name="assignTech">Save changes</button> -->
       <!--
          <a href="testDetailsV2.php?tid=<?php echo $test['id'];?>" type="submit" class="btn btn-primary" name="assignTech">Save changes</a>
                 -->
      </div>
      </form>
      </div>
      
                 </form>
    </div>
  </div>
</div>

    



    </div> 
<?php // endif;?>


</table>
                        


                                </div>
                            </div>

                        </div>
                    </div>

</form>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

           <?php include_once('includes/footer.php');?>

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
<?php include_once('includes/footer2.php');?>







<script>
        
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>